spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university-management-system
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        sql_format: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect